apiVersion: v1
kind: Ingress
metadata:
  name: myapp-ingress
spec:
  rules:
  - host: myapp.com
    http:
      path:
      - backend:
          serviceName: myapp-service
          servicePort: 3000

